repos:
  - repo: local
    hooks:
      - id: make-style
        name: make style
        entry: make style
        language: system
      - id: make-test
        name: make test
        entry: make test
        language: system
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update", "--no-cache"]
      - id: poetry-export
        name: export dev requirements
        args: [ "--with", "dev", "-f", "requirements.txt", "-o", "requirements.dev.txt" ]
      - id: poetry-export
        name: export requirements
        args: ["-f", "requirements.txt", "-o", "requirements.txt" ]