version: 1
disable_existing_loggers: false
formatters:
  default:
    class: logging.Formatter
    format: '%(asctime)s - %(name)s - %(levelname)-8s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
loggers:
  app:
    level: INFO
    handlers: [console]
  uvicorn:
    level: INFO
    handlers: [console]
  gunicorn:
    level: INFO
    handlers: [console]