name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup Poetry
        run: |
          make setup-poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: make install-dev
      - name: Analyse the code style with ruff
        run: make ruff
      - name: Analyse typing with mypy
        run: make mypy
      - name: Analyse security risks with bandit
        run: make bandit
      - name: Run tests
        run: make test-coverage

  build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:build-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:build-cache,mode=max
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}